atom_feats_type: 'cgcnn'
atom_attrs_type: 'z'
structure_format: 'cif'
max_radius: 5
num_neighbors: null

validSplit: 0.1
testSplit: 0.1

number_of_basis: 25
basis_type: "gaussian"
cutoff_basis: False
mul: 32
lmax: 1

in_dim: 103
em_dim: 64

n_conv_layers: 2
n_CAT_layers: 3

batch_size: 256
num_epochs: 300
patience: 100